import sentiment_analysis as sa

tweets_file = input("Enter the name of the file containing tweets: ")
keywords_file = input("Enter the name of the file containing keywords and value: ")

result_list = sa.compute_tweets(tweets_file, keywords_file)
print()
print("Eastern region:")
print("Happiness average:", result_list[0][0])
print("Keywords count:", result_list[0][1])
print("Tweets count:", result_list[0][2])
print()
print("Central region:")
print("Happiness average:", result_list[1][0])
print("Keywords count:", result_list[1][1])
print("Tweets count:", result_list[1][2])
print()
print("Mountain region:")
print("Happiness average:", result_list[2][0])
print("Keywords count:", result_list[2][1])
print("Tweets count:", result_list[2][2])
print()
print("Pacific region:")
print("Happiness average:", result_list[3][0])
print("Keywords count:", result_list[3][1])
print("Tweets count:", result_list[3][2])
print()
